version: '3.1'

services:

  owncloud:
    image: owncloud:latest
    restart: always
    volumes:
      - ./data:/var/www/html
    ports:
      - 10001:80
    links:
      - redis
  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_MAXCONN=10000
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./redis:/var/lib/redis
    
